
'use server';

/**
 * @fileOverview An AI flow to analyze a generated Profit & Loss report and provide business insights.
 *
 * - analyzePLReport - A function that provides an analysis of a P&L report.
 * - AnalyzePLReportInput - The input type for the function.
 * - PLReportAnalysis - The return type for the function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import type { BusinessTransaction } from '@/lib/types';
import type { PLReport } from './generate-pl-report';

// Use z.any() for complex inputs that are already strongly typed in the app
const AnalyzePLReportInputSchema = z.object({
  plReport: z
    .any()
    .describe('The Profit & Loss report object generated by the generatePLReport flow.'),
  transactions: z
    .any()
    .describe('The array of business transactions used to generate the report.'),
});
export type AnalyzePLReportInput = {
    plReport: PLReport;
    transactions: BusinessTransaction[];
};

const PLReportAnalysisSchema = z.object({
  performanceSummary: z.string().describe("A high-level summary of the business's financial performance, including comments on profitability."),
  keyTrends: z.array(z.string()).describe("A list of 2-3 key trends observed, like a significant increase in a specific expense category or notable revenue changes."),
  actionableAdvice: z.string().describe("A concrete, actionable piece of advice based on the analysis. For example, suggesting a review of 'Software' costs if they are disproportionately high."),
  riskAlert: z.string().optional().describe("A potential risk or issue to watch out for, such as costs growing faster than revenue. If no major risks, this can be omitted."),
});
export type PLReportAnalysis = z.infer<typeof PLReportAnalysisSchema>;

export async function analyzePLReport(
  input: AnalyzePLReportInput
): Promise<PLReportAnalysis> {
  return analyzePLReportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzePLReportPrompt',
  input: { schema: z.object({ 
    plReportJson: z.string(),
    transactionsJson: z.string(),
  }) },
  output: { schema: PLReportAnalysisSchema },
  prompt: `You are a virtual CFO for a small business. Your task is to analyze the provided Profit & Loss (P&L) report and the underlying transaction data to give the business owner clear, actionable insights.

P&L Report:
{{{plReportJson}}}

Transactions:
{{{transactionsJson}}}

Based on this data, provide the following analysis in a concise and easy-to-understand manner:

1.  **Performance Summary:** Give a brief, high-level summary of the business's performance. How is the profitability?
2.  **Key Trends:** Identify 2-3 of the most important trends. Is a particular expense category growing too fast? Is a revenue stream performing exceptionally well?
3.  **Actionable Advice:** Provide one concrete, actionable piece of advice. For example: "Your 'Software' subscriptions make up 30% of your expenses. Consider reviewing these for any non-essential services to improve your net profit."
4.  **Risk Alert:** If you see a potential risk (e.g., expenses growing much faster than revenue, declining profit margins), highlight it. If things look healthy, you can omit this.
`,
});

const analyzePLReportFlow = ai.defineFlow(
  {
    name: 'analyzePLReportFlow',
    inputSchema: AnalyzePLReportInputSchema,
    outputSchema: PLReportAnalysisSchema,
  },
  async (input) => {
    // The date is already an ISO string from the client, so no need to convert.
    const transactionsForPrompt = input.transactions.map(t => ({
      ...t,
      date: new Date(t.date).toISOString().split('T')[0]
    }));

    const { output } = await prompt({
        plReportJson: JSON.stringify(input.plReport),
        transactionsJson: JSON.stringify(transactionsForPrompt),
    });
    return output!;
  }
);
