'use server';

/**
 * @fileOverview A flow for converting text to speech using a generative AI model.
 *
 * - textToSpeech - A function that takes text and returns a base64 encoded WAV audio file.
 * - TextToSpeechInput - The input type for the textToSpeech function.
 * - TextToSpeechOutput - The return type for the textToSpeech function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import wav from 'wav';
import { googleAI } from '@genkit-ai/googleai';

const TextToSpeechInputSchema = z.object({
  text: z.string().describe('The text to be converted to speech.'),
});
export type TextToSpeechInput = z.infer<typeof TextToSpeechInputSchema>;

const TextToSpeechOutputSchema = z.object({
  audio: z
    .string()
    .describe(
      "The base64 encoded WAV audio file as a data URI: 'data:audio/wav;base64,...'"
    ),
});
export type TextToSpeechOutput = z.infer<typeof TextToSpeechOutputSchema>;

export async function textToSpeech(
  input: TextToSpeechInput
): Promise<TextToSpeechOutput> {
  return textToSpeechFlow(input);
}

// Helper function to convert PCM buffer to WAV buffer
async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    const bufs: any[] = [];
    writer.on('error', reject);
    writer.on('data', (d) => {
      bufs.push(d);
    });
    writer.on('end', () => {
      resolve(Buffer.concat(bufs).toString('base64'));
    });

    writer.write(pcmData);
    writer.end();
  });
}

// Helper to split text into sentences.
function splitSentences(text: string): string[] {
    if (!text) {
        return [];
    }
    // This regex splits by periods, question marks, and exclamation points, including the delimiter in the result.
    const sentences = text.match(/[^.!?]+[.!?]*/g) || [];
    return sentences.map(s => s.trim()).filter(s => s.length > 0);
}


const textToSpeechFlow = ai.defineFlow(
  {
    name: 'textToSpeechFlow',
    inputSchema: TextToSpeechInputSchema,
    outputSchema: TextToSpeechOutputSchema,
  },
  async ({ text }) => {
    const sentences = splitSentences(text);
    const audioBuffers: Buffer[] = [];

    for (const sentence of sentences) {
        // Add a small delay between requests to avoid hitting rate limits.
        await new Promise(resolve => setTimeout(resolve, 1000)); // 1 second delay

        try {
            const { media } = await ai.generate({
                model: googleAI.model('gemini-2.5-flash-preview-tts'),
                config: {
                    responseModalities: ['AUDIO'],
                    speechConfig: {
                    voiceConfig: {
                        prebuiltVoiceConfig: { voiceName: 'Algenib' },
                    },
                    },
                },
                prompt: sentence,
            });

            if (media) {
                const audioBuffer = Buffer.from(
                    media.url.substring(media.url.indexOf(',') + 1),
                    'base64'
                );
                audioBuffers.push(audioBuffer);
            }
        } catch (e) {
            console.error(`Failed to generate audio for sentence: "${sentence}"`, e);
            // We can choose to either stop or continue. For now, we'll continue.
        }
    }

    if (audioBuffers.length === 0) {
        throw new Error('No audio was generated by the model.');
    }

    const combinedBuffer = Buffer.concat(audioBuffers);
    const wavBase64 = await toWav(combinedBuffer);

    return {
      audio: 'data:audio/wav;base64,' + wavBase64,
    };
  }
);